# Code generated by codegen/generate.ts; DO NOT EDIT.
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional


@dataclass
class Config:
    base_url: str
    authorization: str
    service_name: str
    version: str
    environment: str
    sample_ratio: float
    trace_user_profile: bool


def _env(k: str) -> str:
    return (os.environ.get(k) or "").strip()


def resolve_config_from_env() -> Optional[Config]:
    if _env("OTEL_SDK_DISABLED") == "true":
        return None
    endpoint = _env("OTEL_EXPORTER_OTLP_ENDPOINT") or _env("OWLPANE_INGEST_URL")
    if not endpoint:
        return None
    endpoint = endpoint.rstrip("/")
    service = _env("OTEL_SERVICE_NAME") or "python-app"
    version = _env("OWLPANE_RELEASE") or "0.0.0"
    environment = _env("OWLPANE_ENVIRONMENT") or _env("NODE_ENV") or "development"
    key = _env("OWLPANE_INGEST_KEY")
    auth = f"Bearer {key}" if key else ""
    ratio = 1.0
    if _env("NODE_ENV") == "production":
        ratio = 0.1
    raw = _env("OTEL_TRACES_SAMPLER_ARG")
    if raw:
        try:
            f = float(raw)
            ratio = f if 0 <= f <= 1 else 0.1
        except ValueError:
            ratio = 0.1
    tup = _env("OWLPANE_TRACE_USER_PROFILE").lower() in ("1", "true", "yes")
    return Config(
        base_url=endpoint,
        authorization=auth,
        service_name=service,
        version=version,
        environment=environment,
        sample_ratio=ratio,
        trace_user_profile=tup,
    )
