/**
 * Generates thin-language artifacts from schema/sdk-contract.schema.json
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = path.join(root, "schema", "sdk-contract.schema.json");
const goPkg = path.join(root, "packages", "go", "owlpane");
const pyPkg = path.join(root, "packages", "python", "owlpane");

function write(file: string, content: string): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content, "utf8");
}

function generateGoEnv(): void {
  const content = `// Code generated by codegen/generate.ts; DO NOT EDIT.

package owlpane

import (
	"os"
	"strconv"
	"strings"
)

// Env variable names (sdk-contract.schema.json).
const (
	EnvOtelEndpoint     = "OTEL_EXPORTER_OTLP_ENDPOINT"
	EnvOwlpaneIngestURL = "OWLPANE_INGEST_URL"
	EnvIngestKey        = "OWLPANE_INGEST_KEY"
	EnvServiceName      = "OTEL_SERVICE_NAME"
	EnvEnvironment      = "OWLPANE_ENVIRONMENT"
	EnvRelease          = "OWLPANE_RELEASE"
	EnvSdkDisabled      = "OTEL_SDK_DISABLED"
	EnvTraceUserProfile = "OWLPANE_TRACE_USER_PROFILE"
	EnvNodeEnv          = "NODE_ENV"
	EnvSampleRatio      = "OTEL_TRACES_SAMPLER_ARG"
)

// Config is resolved bootstrap state for OpenTelemetry export.
type Config struct {
	BaseURL            string
	Authorization      string // full "Bearer owl_ing_..." or empty
	ServiceName        string
	Version            string
	Environment        string
	SampleRatio        float64
	TraceUserProfile   bool
}

func trim(s string) string { return strings.TrimSpace(s) }

func env(k string) string { return trim(os.Getenv(k)) }

// ResolveConfigFromEnv returns nil when the SDK should not start.
func ResolveConfigFromEnv() *Config {
	if env(EnvSdkDisabled) == "true" {
		return nil
	}
	endpoint := env(EnvOtelEndpoint)
	if endpoint == "" {
		endpoint = env(EnvOwlpaneIngestURL)
	}
	if endpoint == "" {
		return nil
	}
	endpoint = strings.TrimRight(endpoint, "/")

	service := env(EnvServiceName)
	if service == "" {
		service = "go-app"
	}
	version := env(EnvRelease)
	if version == "" {
		version = "0.0.0"
	}
	environment := env(EnvEnvironment)
	if environment == "" {
		environment = env(EnvNodeEnv)
	}
	if environment == "" {
		environment = "development"
	}

	auth := ""
	if key := env(EnvIngestKey); key != "" {
		auth = "Bearer " + key
	}

	ratio := 1.0
	if nodeEnv := env(EnvNodeEnv); nodeEnv == "production" {
		ratio = 0.1
	}
	if raw := env(EnvSampleRatio); raw != "" {
		if f, err := strconv.ParseFloat(raw, 64); err == nil && f >= 0 && f <= 1 {
			ratio = f
		} else {
			ratio = 0.1
		}
	}

	tup := false
	switch strings.ToLower(env(EnvTraceUserProfile)) {
	case "1", "true", "yes":
		tup = true
	}

	return &Config{
		BaseURL:          endpoint,
		Authorization:    auth,
		ServiceName:      service,
		Version:          version,
		Environment:      environment,
		SampleRatio:      ratio,
		TraceUserProfile: tup,
	}
}
`;
  write(path.join(goPkg, "zz_generated_env.go"), content);
}

function generatePythonConfig(): void {
  const content = `# Code generated by codegen/generate.ts; DO NOT EDIT.
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional


@dataclass
class Config:
    base_url: str
    authorization: str
    service_name: str
    version: str
    environment: str
    sample_ratio: float
    trace_user_profile: bool


def _env(k: str) -> str:
    return (os.environ.get(k) or "").strip()


def resolve_config_from_env() -> Optional[Config]:
    if _env("OTEL_SDK_DISABLED") == "true":
        return None
    endpoint = _env("OTEL_EXPORTER_OTLP_ENDPOINT") or _env("OWLPANE_INGEST_URL")
    if not endpoint:
        return None
    endpoint = endpoint.rstrip("/")
    service = _env("OTEL_SERVICE_NAME") or "python-app"
    version = _env("OWLPANE_RELEASE") or "0.0.0"
    environment = _env("OWLPANE_ENVIRONMENT") or _env("NODE_ENV") or "development"
    key = _env("OWLPANE_INGEST_KEY")
    auth = f"Bearer {key}" if key else ""
    ratio = 1.0
    if _env("NODE_ENV") == "production":
        ratio = 0.1
    raw = _env("OTEL_TRACES_SAMPLER_ARG")
    if raw:
        try:
            f = float(raw)
            ratio = f if 0 <= f <= 1 else 0.1
        except ValueError:
            ratio = 0.1
    tup = _env("OWLPANE_TRACE_USER_PROFILE").lower() in ("1", "true", "yes")
    return Config(
        base_url=endpoint,
        authorization=auth,
        service_name=service,
        version=version,
        environment=environment,
        sample_ratio=ratio,
        trace_user_profile=tup,
    )
`;
  write(path.join(pyPkg, "_generated_config.py"), content);
}

function readReleaseVersion(): string {
  const nodePkg = path.join(root, "packages", "node", "package.json");
  return JSON.parse(fs.readFileSync(nodePkg, "utf8")).version as string;
}

function generateInstallSnippets(): void {
  const v = readReleaseVersion();
  const snippets = {
    version: 1,
    go: {
      module: "github.com/balaji-singh/owlpane-sdk/packages/go/owlpane",
      goGet: `go get github.com/balaji-singh/owlpane-sdk/packages/go@v${v}`,
      env: [
        "OTEL_EXPORTER_OTLP_ENDPOINT=https://ingest.example.com",
        "OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf",
        "OWLPANE_INGEST_KEY=owl_ing_…",
        "OTEL_SERVICE_NAME=my-service",
        "OWLPANE_ENVIRONMENT=production",
      ],
      code: `import "github.com/balaji-singh/owlpane-sdk/packages/go/owlpane"

shutdown, err := owlpane.Start(context.Background(), nil)
// … app …
_ = shutdown(context.Background())`,
    },
    python: {
      package: "owlpane",
      pip: `pip install owlpane==${v}`,
      env: [
        "OTEL_EXPORTER_OTLP_ENDPOINT=https://ingest.example.com",
        "OWLPANE_INGEST_KEY=owl_ing_…",
        "OTEL_SERVICE_NAME=my-service",
        "OWLPANE_ENVIRONMENT=production",
      ],
    },
    node: {
      package: "@owlpane/node",
      npm: `npm install @owlpane/node@${v}`,
      note: "Hand-written full SDK in packages/node",
    },
    browser: {
      package: "@owlpane/browser",
      npm: `npm install @owlpane/browser@${v}`,
    },
    java: {
      status: "env-only",
      maven: "com.owlpane:owlpane-java (thin starter — not on Maven Central yet)",
      env: [
        "OTEL_EXPORTER_OTLP_ENDPOINT=https://ingest.example.com",
        "OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf",
        "OWLPANE_INGEST_KEY=owl_ing_…",
        "OTEL_SERVICE_NAME=my-service",
      ],
      note: "Use OpenTelemetry Java agent + env; owlpane-java library ships in a later release.",
    },
    ruby: {
      status: "env-only",
      gem: "owlpane (RubyGems — not published yet)",
      env: [
        "OTEL_EXPORTER_OTLP_ENDPOINT=https://ingest.example.com",
        "OWLPANE_INGEST_KEY=owl_ing_…",
        "OTEL_SERVICE_NAME=my-service",
      ],
    },
  };
  write(
    path.join(root, "schema", "install-snippets.json"),
    JSON.stringify(snippets, null, 2) + "\n",
  );
}

function main(): void {
  if (!fs.existsSync(schemaPath)) {
    console.error("missing schema:", schemaPath);
    process.exit(1);
  }
  JSON.parse(fs.readFileSync(schemaPath, "utf8"));
  generateGoEnv();
  generatePythonConfig();
  generateInstallSnippets();
  console.log("codegen: ok");
}

main();
