// Code generated by codegen/generate.ts; DO NOT EDIT.

package owlpane

import (
	"os"
	"strconv"
	"strings"
)

// Env variable names (sdk-contract.schema.json).
const (
	EnvOtelEndpoint     = "OTEL_EXPORTER_OTLP_ENDPOINT"
	EnvOwlpaneIngestURL = "OWLPANE_INGEST_URL"
	EnvIngestKey        = "OWLPANE_INGEST_KEY"
	EnvServiceName      = "OTEL_SERVICE_NAME"
	EnvEnvironment      = "OWLPANE_ENVIRONMENT"
	EnvRelease          = "OWLPANE_RELEASE"
	EnvSdkDisabled      = "OTEL_SDK_DISABLED"
	EnvTraceUserProfile = "OWLPANE_TRACE_USER_PROFILE"
	EnvNodeEnv          = "NODE_ENV"
	EnvSampleRatio      = "OTEL_TRACES_SAMPLER_ARG"
)

// Config is resolved bootstrap state for OpenTelemetry export.
type Config struct {
	BaseURL            string
	Authorization      string // full "Bearer owl_ing_..." or empty
	ServiceName        string
	Version            string
	Environment        string
	SampleRatio        float64
	TraceUserProfile   bool
}

func trim(s string) string { return strings.TrimSpace(s) }

func env(k string) string { return trim(os.Getenv(k)) }

// ResolveConfigFromEnv returns nil when the SDK should not start.
func ResolveConfigFromEnv() *Config {
	if env(EnvSdkDisabled) == "true" {
		return nil
	}
	endpoint := env(EnvOtelEndpoint)
	if endpoint == "" {
		endpoint = env(EnvOwlpaneIngestURL)
	}
	if endpoint == "" {
		return nil
	}
	endpoint = strings.TrimRight(endpoint, "/")

	service := env(EnvServiceName)
	if service == "" {
		service = "go-app"
	}
	version := env(EnvRelease)
	if version == "" {
		version = "0.0.0"
	}
	environment := env(EnvEnvironment)
	if environment == "" {
		environment = env(EnvNodeEnv)
	}
	if environment == "" {
		environment = "development"
	}

	auth := ""
	if key := env(EnvIngestKey); key != "" {
		auth = "Bearer " + key
	}

	ratio := 1.0
	if nodeEnv := env(EnvNodeEnv); nodeEnv == "production" {
		ratio = 0.1
	}
	if raw := env(EnvSampleRatio); raw != "" {
		if f, err := strconv.ParseFloat(raw, 64); err == nil && f >= 0 && f <= 1 {
			ratio = f
		} else {
			ratio = 0.1
		}
	}

	tup := false
	switch strings.ToLower(env(EnvTraceUserProfile)) {
	case "1", "true", "yes":
		tup = true
	}

	return &Config{
		BaseURL:          endpoint,
		Authorization:    auth,
		ServiceName:      service,
		Version:          version,
		Environment:      environment,
		SampleRatio:      ratio,
		TraceUserProfile: tup,
	}
}
