#!/usr/bin/env node
/**
 * Creates dogfood console projects + ingest keys (same flow as Projects & keys → New project).
 *
 *   node scripts/onboard-dogfood.mjs --write-env
 *
 * Env:
 *   OWLPANE_API_URL          default http://127.0.0.1:4100
 *   OWLPANE_ONBOARD_EMAIL    default scale@owlpane.test
 *   OWLPANE_ONBOARD_PASSWORD default owlpane
 *   OWLPANE_ORG_SLUG         default scale
 *   OWLPANE_INGEST_URL       written to .env (default http://127.0.0.1:4318)
 *   OWLPANE_ENVIRONMENT      default development
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const examplesRoot = join(__dir, "..");
const manifest = JSON.parse(
  readFileSync(join(examplesRoot, "dogfood.manifest.json"), "utf8"),
);

const API = (process.env.OWLPANE_API_URL ?? "http://127.0.0.1:4100").replace(/\/+$/, "");
const EMAIL = process.env.OWLPANE_ONBOARD_EMAIL ?? "scale@owlpane.test";
const PASSWORD = process.env.OWLPANE_ONBOARD_PASSWORD ?? "owlpane";
const ORG_SLUG = (process.env.OWLPANE_ORG_SLUG ?? "scale").trim().toLowerCase();
const ENVIRONMENT = process.env.OWLPANE_ENVIRONMENT ?? "development";
const INGEST_URL = (process.env.OWLPANE_INGEST_URL ?? "http://127.0.0.1:4318").replace(/\/+$/, "");
const writeEnv = process.argv.includes("--write-env");

async function api(path, { method = "GET", token, body } = {}) {
  const res = await fetch(`${API}${path}`, {
    method,
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      "User-Agent": "owlpane-sdk-dogfood-onboard/1.0",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  let data;
  try {
    data = text ? JSON.parse(text) : null;
  } catch {
    data = { raw: text };
  }
  if (!res.ok) {
    const msg = data?.message ?? data?.error ?? text ?? res.statusText;
    throw new Error(`${method} ${path} → ${res.status}: ${msg}`);
  }
  return data;
}

async function main() {
  const login = await api("/v1/auth/login", {
    method: "POST",
    body: { email: EMAIL, password: PASSWORD },
  });
  const token = login.sessionToken;
  if (!token) {
    throw new Error(
      "Login did not return sessionToken (MFA enabled?). Set OWLPANE_SESSION_TOKEN from the console.",
    );
  }

  const { orgs } = await api("/v1/me", { token });
  const org =
    orgs.find((o) => o.slug?.toLowerCase() === ORG_SLUG) ??
    orgs.find((o) => o.name?.toLowerCase() === ORG_SLUG) ??
    orgs[0];
  if (!org) throw new Error("No organization on this account");

  const { projects } = await api(`/v1/orgs/${org.id}/projects`, { token });
  const keysOut = {};

  for (const app of manifest.apps) {
    const name = app.project;
    let project = projects.find(
      (p) => p.name === name && p.environment === ENVIRONMENT,
    );
    let ingestKey;

    if (!project) {
      const created = await api(`/v1/orgs/${org.id}/projects`, {
        method: "POST",
        token,
        body: { name, environment: ENVIRONMENT },
      });
      project = created.project;
      ingestKey = created.ingestKey;
      console.log(`Created project ${name} (${ENVIRONMENT})`);
    } else {
      const keyRes = await api(`/v1/projects/${project.id}/keys`, {
        method: "POST",
        token,
        body: { name: "sdk-dogfood-examples" },
      });
      ingestKey = keyRes.key;
      console.log(`Project ${name} exists — issued new ingest key`);
    }

    keysOut[app.ingestKeyEnv] = ingestKey;
  }

  if (writeEnv) {
    const lines = [
      "# Auto-generated by scripts/onboard-dogfood.mjs — one console project per SDK example.",
      `OWLPANE_INGEST_URL=${INGEST_URL}`,
      `OWLPANE_ENVIRONMENT=${ENVIRONMENT}`,
      "",
      ...manifest.apps.map((a) => `${a.ingestKeyEnv}=${keysOut[a.ingestKeyEnv]}`),
      "",
    ];
    const envPath = join(examplesRoot, ".env");
    writeFileSync(envPath, lines.join("\n"), "utf8");
    console.log(`Wrote ${envPath}`);
  } else {
    console.log("\nIngest keys (also use --write-env to update examples/.env):\n");
    for (const app of manifest.apps) {
      console.log(`  ${app.project}: ${keysOut[app.ingestKeyEnv]}`);
    }
  }

  console.log(`\nOrg: ${org.name} (${org.slug}) · open Projects & keys to verify.`);
}

main().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
